
# SEO settings
title: "Sten Sootla's blog"
keywords: "deep learning, neural networks, mathematics, computer programming, algorithms"
url: http://sootlasten.github.io # site url
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/sootlasten
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
kramdown:
    syntax_highlighter_opts:
        disable : true
highlighter : rouge
# highlighter: none

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Sten Sootla"
  job      : "rather unfocussed enthusiast of machine learning and a few other things"
  thumb    : /images/author.jpg
  email    : stensootla@gmail.com
  url      : http://sootlasten.github.io
  github   : http://github.com/sootlasten

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
